from Classes import Grade, Teacher, Student, School
if __name__ == '__main__':
    grade1 = Grade('5 A', 'Иванова А. А., Петрова Т.Т', 'Сидоров Г.Г, Осинов В.В')
    grade2 = Grade('5 Б', 'Иванова А. А., Петрова Т. Т', 'Дубов П.П, Зубной В.Ч')
    student1 = Student('5 A', 'Сидоров Г.Г', 'Математика, Русский язык', 'Сидорова Я. О., Сидоров П. А')
    student2 = Student('5 А', 'Осинов В. В', 'Математика, Русский язык', 'Осинова Ю. А., Осинов Ф. А')
    student3 = Student('5 Б', 'Дубов П. П', 'Математика, Русский язык', 'Дубова А. О., Дубов С. А')
    student4 = Student('5 Б', 'Зубной В. Ч', 'Математика, Русский язык', 'Зубная Е. Е., Зубной М. И')
    school = School(2, '5 A, 5 Б')
    grade1.show_students()
    grade2.show_students()
    student1.show_parents()
    student1.show_subj()
    student2.show_parents()
    student2.show_subj()
    student3.show_parents()
    student3.show_subj()
    student4.show_parents()
    student4.show_subj()
    grade1.show_teachers()
    grade2.show_teachers()
    school.get_classes()